title: Curious Platypus
author: Parichay Mazumdar
email: mazumdar.parichay@gmail.com
description: >
  Letting curiosity get the best of you.

minima:
  social_links:
    github: mazpar 
    linkedin: parichaymazumdar


# url: "https://cthoyt.com"

paginate: true
paginate_path: "/blog/page:num/"
show_excerpts: true

markdown: kramdown

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
